<h1 style="color: darkblue; text-align: center; font-family: Arial, sans-serif; font-size: 32px;">
  Creation of arrays using numpy
</h1>


In [1]:
#EXP NO: 5

In [2]:
#Aim: To create and manipulate arrays using NumPy for efficient numerical computations in Python.

In [3]:
#Name: YASH E JAYALE
#Roll no: 24
#sec: A
#subject: EMERGING TECH. LAB - I

In [4]:
import numpy as np


In [5]:
# 1D Array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1d)

# 2D Array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2d)

# 3D Array
arr3d = np.array([[[1], [2]], [[3], [4]]])
print("3D Array:\n", arr3d)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1]
  [2]]

 [[3]
  [4]]]


In [6]:
# Array of zeros
zeros_arr = np.zeros((2, 3))
print("Zeros Array:\n", zeros_arr)

# Array of ones
ones_arr = np.ones((3, 3))
print("Ones Array:\n", ones_arr)

# Identity matrix
identity_arr = np.eye(3)
print("Identity Matrix:\n", identity_arr)

# Range of numbers
range_arr = np.arange(0, 10, 2)
print("Array with np.arange:\n", range_arr)

# Evenly spaced values
linspace_arr = np.linspace(0, 1, 5)
print("Array with np.linspace:\n", linspace_arr)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array with np.arange:
 [0 2 4 6 8]
Array with np.linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [7]:
print("Shape of arr2d:", arr2d.shape)
print("Size of arr2d:", arr2d.size)
print("Data type of arr2d:", arr2d.dtype)


Shape of arr2d: (2, 3)
Size of arr2d: 6
Data type of arr2d: int32


In [8]:
reshaped = arr2d.reshape(3, 2)
print("Reshaped Array:\n", reshaped)

# Slicing
print("First row of arr2d:", arr2d[0])
print("Element at row 1, col 2:", arr2d[1, 2])


Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
First row of arr2d: [1 2 3]
Element at row 1, col 2: 6


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Square root:", np.sqrt(a))


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Square root: [1.         1.41421356 1.73205081]


### ✅ Conclusion:
This practical covered the creation of 1D, 2D, and 3D arrays using NumPy, along with array operations like reshaping, slicing, and arithmetic.
